### ISSUE TITLE
Peer-Review Homework 2

### ISSUE THREAD

**Issue by funkedavid82** [STAT545-UBC-students/hw02-zeeva85#1]
Peer-Review HW-02 for zeeva85

Good job @zeeva85  
----------------------------------------------------
Topic                       | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|------------------|
**Coding style**            | :heavy_check_mark: |  |  |
**Coding strategy**         |  | :heavy_check_mark: |  |
**Presentation: graphs**    |  | :heavy_check_mark:  | |
**Presentation: tables**    |  | :heavy_check_mark:  |  |
**Achievement, creativity** |  |  | :heavy_check_mark: |
**Ease of access**          | :heavy_check_mark: |  |  |

Remarks:

- *Elaborate on above, esp. for "needs work."*
Your graphs look great, but it will be better if you can do a lot different from what we did in class.
Full commenting and explaining of code commands will make your work more clearer.

- *Some specific praise?*
Your file was easily accessible and you were able to show more of what was done in class. 

- *Something I learned?*
Good job, I learnt a new command `is.list`, `is.array` and so on. I didn't know this before.

- *Specific constructive criticism?*
You may want to try different plot types from what was done in class. These plots don't seems new to me.

- *Something I know and that you, my peer, might like to know because it is relevant to something you struggled with.*
You may also want to use the command `facet_wrap` or `facet_grid` to stratify the bar plot as well

**Comment by zeeva85** [comment]
thank you @funkedavid82, I agree there are less plots, the assignment for week 2 is:-

Homework 02: Explore Gapminder and use dplyr not using ggplot, ggplot is week 3. [see here](http://stat545.com/Classroom/assignments/hw03/hw03.html)
