### ISSUE TITLE
Peer Review HW02

### ISSUE THREAD

**Issue by MalcolmNSB** [STAT545-UBC-students/hw02-zeeva85#2]
Peer-Review HW-02 for zeeva85

----------------------------------------------------
Topic                       | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style**            | :heavy_check_mark: |  |  |
**Coding strategy**         | :heavy_check_mark:  | |  |
**Presentation: graphs**    |  :heavy_check_mark:|  |  |
**Presentation: tables**    |  :heavy_check_mark: |  |  |
**Achievement, creativity** | :heavy_check_mark: |  |  |
**Ease of access**          | :heavy_check_mark: |  |  |

Remarks:

- There is a lot of great information here - as a relative beginner to "data analysis", it was interesting to see your discussion on "Sanity check for missing values", it's not something I was aware of! It was also nice to learn about the "names()", "unique()", "droplevels()" functions.
- The code commentary is very useful - without it, I would have had trouble trying to understand what the code was doing in some places.
- I felt a couple of graphs had too much information. For example, your "scatter plot + boxplot + violin, separated by continent", it seems like the density of information is a little high (for me at least) to understand. But it was nice to see all the variations of plots (including the pie chart which I hadn't seen yet!). Great work.

**Comment by zeeva85** [comment]
@MalcolmNSB. Thank you :pray:  for your helpful suggestions, I will definitely improve on the above mentioned.
